### Clear cache
GET {{workHoursScrapperBaseUri}}/api/clear-cache

### Scrape
GET {{workHoursScrapperBaseUri}}/api/scrape

### Scrape Konzum
GET {{workHoursScrapperBaseUri}}/api/scrape/konzum

### Scrape Studenac
GET {{workHoursScrapperBaseUri}}/api/scrape/studenac

### Scrape Kaufland
GET {{workHoursScrapperBaseUri}}/api/scrape/kaufland

### Scrape Eurospin
GET {{workHoursScrapperBaseUri}}/api/scrape/eurospin

### Scrape Spar
GET {{workHoursScrapperBaseUri}}/api/scrape/spar

### Scrape Lidl
GET {{workHoursScrapperBaseUri}}/api/scrape/lidl

### Scrape Plodine
GET {{workHoursScrapperBaseUri}}/api/scrape/plodine

### Scrape Tommy
GET {{workHoursScrapperBaseUri}}/api/scrape/tommy

### Flare Bypasser 1
POST http://flare-bypasser.flycast/v1
Content-Type: application/json

{
  "cmd": "request.get",
  "url": "https://www.studenac.hr/trgovine/478/t514-bale-valle",
  "maxTimeout": 60000
}

### Flare Bypasser 2
POST http://flare-bypasser.flycast/v1
Content-Type: application/json

{
  "cmd": "request.get",
  "url": "https://www.studenac.hr/trgovine/1256/t991-bale",
  "maxTimeout": 60000
}

### Konzum locations
GET https://trgovine.konzum.hr/api/locations