### Scrape
GET {{workHoursScrapperBaseUri}}/api/scrape

### Scrape Konzum
GET {{workHoursScrapperBaseUri}}/api/scrape/konzum

### Scrape Studenac
GET {{workHoursScrapperBaseUri}}/api/scrape/studenac

### Scrape Kaufland
GET {{workHoursScrapperBaseUri}}/api/scrape/kaufland