# fly.toml app configuration file generated for workhours-scrapper on 2024-06-29T15:20:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workhours-scrapper'
primary_region = 'otp'
swap_size_mb = 2048

[build]

[env]
  FORMAT = 'letter'
  JAVASCRIPT = 'false'
  TIMEOUT = '15'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 5
    soft_limit = 3

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
